import React from "react";
import {
  Lock,
  EyeOff,
  CheckCircle2,
  XCircle,
  FileText,
  KeyRound,
  Database,
  Server,
  Cpu
} from "lucide-react";

export default function DataPrivacy() {

  const whatWeReceive = [
    {
      field: "transaction_token",
      label: "Synthetic Transaction Identifier",
      desc: "Opaque token generated by the bank (e.g. ABA-TX-10029). No account numbers exposed.",
      purpose: "Idempotency & state machine reference"
    },
    {
      field: "amount & currency",
      label: "Settlement Value",
      desc: "Gross transaction amount and ISO currency code (USD, KHR).",
      purpose: "Numerical outlier detection"
    },
    {
      field: "payment_method",
      label: "Payment Rails Instrument",
      desc: "Protocol classification: KHQR, Card, Bank Transfer, Mobile.",
      purpose: "Channel risk scoring"
    },
    {
      field: "distance",
      label: "Haversine Geolocation Delta",
      desc: "Computed radial kilometers between terminal IP/GPS and home baseline.",
      purpose: "Impossible speed & border anomaly analysis"
    },
    {
      field: "time_delta",
      label: "Elapsed Inactivity Period",
      desc: "Floating-point hours since prior recognized transaction on account.",
      purpose: "Account reactivation burst detection"
    },
    {
      field: "merchant_risk",
      label: "Merchant Category Score",
      desc: "Heuristic classification index between 0.00 and 1.00 based on MCC code.",
      purpose: "High-risk counterparty defense"
    },
    {
      field: "device_trust",
      label: "Cryptographic Fingerprint Confidence",
      desc: "Normalized 0.00 to 1.00 score indicating device consistency.",
      purpose: "Synthetic identity & credential stuffing defense"
    }
  ];

  const whatWeNeverReceive = [
    {
      item: "Customer Passwords & PINs",
      desc: "Cardholder banking passwords, transaction PINs, and ATM security codes remain strictly inside the bank's core HSM.",
      icon: Lock
    },
    {
      item: "One-Time Passcodes (OTP)",
      desc: "SMS OTP and authenticator codes are sent and verified directly by the bank's identity provider. SentinelPay never inspects challenge payloads.",
      icon: KeyRound
    },
    {
      item: "Primary Account Numbers (PAN / CVV)",
      desc: "Raw 16-digit credit card numbers and 3-digit CVV security codes are never transmitted to or persisted in SentinelPay databases.",
      icon: EyeOff
    },
    {
      item: "Customer KYC & Identification",
      desc: "National ID cards, passports, selfies, home physical addresses, and tax numbers stay with the originating financial institution.",
      icon: FileText
    },
    {
      item: "Account Balances & Full Net Worth",
      desc: "Total checking balances, savings holdings, loans, and investment profiles are completely invisible to SentinelPay.",
      icon: Database
    },
    {
      item: "Personal Address Book & Contacts",
      desc: "Mobile device address books, call logs, and SMS messages are never requested or accessed.",
      icon: XCircle
    }
  ];

  return (
    <div className="page-container">
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
          <span className="section-label">Architecture &bull; Data Governance</span>
          <span style={{ fontSize: 11, background: "rgba(16, 185, 129, 0.08)", color: "var(--emerald)", padding: "2px 8px", borderRadius: 4, fontWeight: 700 }}>
            PRIVACY BY DESIGN
          </span>
        </div>
        <h1 className="page-title">Data Minimization &amp; Privacy Architecture</h1>
        <p className="page-subtitle">
          SentinelPay operates on strict data minimization principles. Financial institutions retain full custody of customer identity and secrets, transmitting only mathematical behavioral features required for ML risk scoring.
        </p>
      </div>

      {/* High-Level Architecture Contrast Banner */}
      <div className="bezel-shell" style={{ marginBottom: 24 }}>
        <div className="bezel-core" style={{ padding: "24px 28px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 20, alignItems: "center" }}>
            {/* Bank Custody Column */}
            <div style={{ padding: "18px 20px", borderRadius: 14, background: "rgba(15, 23, 42, 0.03)", border: "1px solid rgba(15, 23, 42, 0.08)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8, color: "var(--text-1)" }}>
                <Server style={{ width: 18, height: 18, color: "var(--cobalt)" }} />
                <h3 style={{ fontSize: 14, fontWeight: 800 }}>External Financial Institution</h3>
              </div>
              <p style={{ fontSize: 12, color: "var(--text-2)", lineHeight: 1.5, marginBottom: 12 }}>
                Retains absolute ownership over:
              </p>
              <ul style={{ fontSize: 12, color: "var(--text-2)", display: "flex", flexDirection: "column", gap: 6, paddingLeft: 16 }}>
                <li>Customer identity &amp; official KYC documents</li>
                <li>Account balances &amp; deposit ledgers</li>
                <li>Primary authentication (PIN, Biometrics, OTP)</li>
                <li>Final fund transfer settlement authorization</li>
              </ul>
            </div>

            {/* Privacy Bridge */}
            <div style={{ textAlign: "center", padding: "10px" }}>
              <div style={{ display: "inline-flex", flexDirection: "column", alignItems: "center", gap: 6 }}>
                <div style={{ width: 36, height: 36, borderRadius: "50%", background: "var(--cobalt-light)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--cobalt)" }}>
                  <Lock style={{ width: 18, height: 18 }} />
                </div>
                <span style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-mono)", color: "var(--cobalt)" }}>
                  SECURE ZERO-PII GATEWAY
                </span>
                <span style={{ fontSize: 11, color: "var(--text-3)", maxWidth: 180 }}>
                  Only mathematical vectors pass through the integration barrier
                </span>
              </div>
            </div>

            {/* SentinelPay AI Scope Column */}
            <div style={{ padding: "18px 20px", borderRadius: 14, background: "rgba(37, 99, 235, 0.03)", border: "1px solid rgba(37, 99, 235, 0.15)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8, color: "var(--cobalt)" }}>
                <Cpu style={{ width: 18, height: 18 }} />
                <h3 style={{ fontSize: 14, fontWeight: 800 }}>SentinelPay AI Intelligence Core</h3>
              </div>
              <p style={{ fontSize: 12, color: "var(--text-2)", lineHeight: 1.5, marginBottom: 12 }}>
                Processes only non-sensitive risk features:
              </p>
              <ul style={{ fontSize: 12, color: "var(--text-2)", display: "flex", flexDirection: "column", gap: 6, paddingLeft: 16 }}>
                <li>XGBoost &amp; Random Forest inference on 9 scaled features</li>
                <li>Local TreeSHAP marginal Shapley contributions</li>
                <li>Threshold matrix policy (APPROVE / STEP-UP / BLOCK)</li>
                <li>Audit logging and retraining feedback loops</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      {/* Side-by-Side Visual Comparison Matrix */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))", gap: 20 }}>
        {/* Left: What SentinelPay Receives */}
        <div className="surface-card">
          <div style={{ display: "flex", alignItems: "center", gap: 10, paddingBottom: 14, borderBottom: "1px solid var(--shell-bg)", marginBottom: 16 }}>
            <div style={{ width: 32, height: 32, borderRadius: 8, background: "var(--emerald-light)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--emerald)" }}>
              <CheckCircle2 style={{ width: 18, height: 18 }} />
            </div>
            <div>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: "var(--text-1)" }}>
                What SentinelPay Receives
              </h2>
              <span style={{ fontSize: 11, color: "var(--text-3)" }}>
                Permitted non-PII behavioral telemetry
              </span>
            </div>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {whatWeReceive.map((item, i) => (
              <div
                key={i}
                style={{
                  padding: "10px 12px",
                  borderRadius: 10,
                  background: "var(--shell-bg)",
                  border: "1px solid var(--shell-border)",
                  fontSize: 12
                }}
              >
                <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 3 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                    <CheckCircle2 style={{ width: 14, height: 14, color: "var(--emerald)", flexShrink: 0 }} />
                    <strong style={{ color: "var(--text-1)" }}>{item.label}</strong>
                  </div>
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, color: "var(--cobalt)", background: "#FFFFFF", padding: "1px 6px", borderRadius: 4, border: "1px solid rgba(15, 23, 42, 0.06)" }}>
                    {item.field}
                  </span>
                </div>
                <div style={{ fontSize: 11.5, color: "var(--text-2)", marginBottom: 4, paddingLeft: 20 }}>
                  {item.desc}
                </div>
                <div style={{ fontSize: 10.5, color: "var(--text-3)", paddingLeft: 20, fontStyle: "italic" }}>
                  Purpose: {item.purpose}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right: What SentinelPay Does NOT Receive */}
        <div className="surface-card">
          <div style={{ display: "flex", alignItems: "center", gap: 10, paddingBottom: 14, borderBottom: "1px solid var(--shell-bg)", marginBottom: 16 }}>
            <div style={{ width: 32, height: 32, borderRadius: 8, background: "var(--rose-light)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--rose)" }}>
              <XCircle style={{ width: 18, height: 18 }} />
            </div>
            <div>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: "var(--text-1)" }}>
                What SentinelPay NEVER Receives
              </h2>
              <span style={{ fontSize: 11, color: "var(--text-3)" }}>
                Zero-tolerance personal data &amp; credentials
              </span>
            </div>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {whatWeNeverReceive.map((item, i) => {
              const Icon = item.icon;
              return (
                <div
                  key={i}
                  style={{
                    padding: "12px 14px",
                    borderRadius: 10,
                    background: "rgba(239, 68, 68, 0.03)",
                    border: "1px solid rgba(239, 68, 68, 0.12)",
                    fontSize: 12
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                    <div style={{ width: 22, height: 22, borderRadius: 6, background: "var(--rose-light)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--rose)", flexShrink: 0 }}>
                      <Icon style={{ width: 12, height: 12 }} />
                    </div>
                    <strong style={{ color: "var(--rose)", fontSize: 12.5 }}>{item.item}</strong>
                  </div>
                  <p style={{ fontSize: 11.5, color: "var(--text-2)", lineHeight: 1.5, paddingLeft: 30 }}>
                    {item.desc}
                  </p>
                </div>
              );
            })}
          </div>

          {/* Compliance Callout */}
          <div style={{ marginTop: 18, padding: "12px 14px", borderRadius: 10, background: "var(--shell-bg)", border: "1px solid var(--shell-border)", fontSize: 11.5, color: "var(--text-2)", lineHeight: 1.5 }}>
            <strong style={{ color: "var(--text-1)" }}>Regulatory Compliance:</strong> By decoupling customer authentication from risk scoring, SentinelPay naturally complies with strict banking secrecy laws, PCI-DSS Level 1 tokenization rules, and modern personal data protection regulations.
          </div>
        </div>
      </div>
    </div>
  );
}
